import React, { useState } from 'react';
import { TravelGuide } from '../types';
import { Button } from './ui/Button';
import { ArrowLeft, Thermometer, Info, Map as MapIcon, Clock, Lightbulb, ShieldCheck, Utensils, Camera, Share2, Heart, Sparkles, X, MessageCircle, Twitter, Link2, AlertCircle } from 'lucide-react';

interface ItineraryViewProps {
  guide: TravelGuide;
  onBack: () => void;
  onSave?: (guide: TravelGuide) => void;
  isSaved?: boolean;
}

export const ItineraryView: React.FC<ItineraryViewProps> = ({ guide, onBack, onSave, isSaved }) => {
  const [isShareModalOpen, setIsShareModalOpen] = useState(false);
  const [isSaveConfirmOpen, setIsSaveConfirmOpen] = useState(false);

  // Helper to generate a picsum url based on keywords seeded by the city name
  const getCityImage = (keyword: string) => `https://picsum.photos/seed/${encodeURIComponent(guide.city + keyword)}/800/400`;
  // Updated: Use encodeURIComponent to handle prompts with spaces/special chars correctly
  const getSmallImage = (seed: string) => `https://picsum.photos/seed/${encodeURIComponent(seed)}/200/200`;
  const getItineraryImage = (seed: string) => `https://picsum.photos/seed/${encodeURIComponent(seed)}/400/200`;

  const generateShareText = () => {
    return `Check out this amazing itinerary for ${guide.city}, ${guide.country}! ${guide.introduction}\n\nGenerated by Travel Buddy.`;
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Trip to ${guide.city}`,
          text: generateShareText(),
          url: window.location.href,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      setIsShareModalOpen(true);
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(`${generateShareText()} ${window.location.href}`);
    alert("Trip details copied to clipboard!");
    setIsShareModalOpen(false);
  };

  const handleWhatsAppShare = () => {
    const text = encodeURIComponent(`${generateShareText()} ${window.location.href}`);
    window.open(`https://wa.me/?text=${text}`, '_blank');
    setIsShareModalOpen(false);
  };

  const handleTwitterShare = () => {
    const text = encodeURIComponent(generateShareText());
    const url = encodeURIComponent(window.location.href);
    window.open(`https://twitter.com/intent/tweet?text=${text}&url=${url}`, '_blank');
    setIsShareModalOpen(false);
  };

  const onSaveClick = () => {
    if (isSaved) return;
    setIsSaveConfirmOpen(true);
  };

  const handleConfirmSave = () => {
    if (onSave) {
      onSave(guide);
    }
    setIsSaveConfirmOpen(false);
  };

  return (
    <div className="space-y-8 animate-in slide-in-from-right-8 duration-500 relative">
      
      {/* Header with Back Button */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <Button variant="ghost" onClick={onBack} className="p-2 h-auto rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 dark:text-slate-200">
            <ArrowLeft size={24} />
          </Button>
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white leading-none">{guide.city}</h2>
            <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">{guide.country}</p>
          </div>
        </div>
        <div className="flex space-x-2">
           {onSave && (
             <Button 
               variant={isSaved ? "primary" : "outline"} 
               onClick={onSaveClick}
               disabled={isSaved}
               className="p-2 px-3 h-10 text-sm"
             >
               <Heart className={`w-4 h-4 mr-2 ${isSaved ? 'fill-current' : ''}`} />
               {isSaved ? 'Saved' : 'Save'}
             </Button>
           )}
           <Button variant="secondary" onClick={() => setIsShareModalOpen(true)} className="p-2 h-10 w-10">
             <Share2 className="w-4 h-4" />
           </Button>
        </div>
      </div>

      {/* Hero Image & Localized Welcome */}
      <div className="relative rounded-3xl overflow-hidden shadow-2xl h-80 group">
        <img src={getCityImage('skyline')} alt={guide.city} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-1000" />
        <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/40 to-transparent flex flex-col justify-end p-8">
           <div className="animate-in slide-in-from-bottom-6 duration-700 delay-100">
             <h1 className="text-4xl md:text-6xl font-black text-white mb-2 tracking-tight drop-shadow-lg">
               {guide.welcomeMessage || `Welcome to ${guide.city}`}
             </h1>
             <div className="bg-white/10 backdrop-blur-md rounded-xl p-4 text-white border border-white/20 mt-4 max-w-2xl">
               <p className="font-medium text-lg leading-relaxed shadow-sm">
                 {guide.introduction}
               </p>
             </div>
           </div>
        </div>
      </div>

      {/* Weather Card */}
      <div className="bg-gradient-to-br from-brand-500 to-cyan-400 rounded-3xl p-6 text-white shadow-xl shadow-brand-500/20">
        <div className="flex justify-between items-start">
          <div>
            <div className="flex items-center space-x-2 mb-1 opacity-90">
              <Thermometer size={18} />
              <span className="text-sm font-semibold uppercase tracking-wider">Current Vibes</span>
            </div>
            <div className="text-5xl font-bold mb-1 tracking-tight">{guide.weather.temperature}</div>
            <div className="text-xl font-medium opacity-90 flex items-center">
              <Sparkles className="w-4 h-4 mr-2" />
              {guide.weather.condition}
            </div>
          </div>
          <div className="text-right max-w-[50%]">
             <span className="inline-block bg-white/20 backdrop-blur-sm rounded-lg px-3 py-1 text-xs font-bold uppercase tracking-wide border border-white/30">
               Packing Check
             </span>
             <p className="mt-2 text-sm leading-snug font-medium opacity-95">
               {guide.weather.packingSuggestion}
             </p>
          </div>
        </div>
      </div>

      {/* Attractions Grid */}
      <div>
        <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-4 flex items-center">
          <Camera className="mr-2 text-brand-600 dark:text-brand-400" size={20} /> Must-Visit Spots
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {guide.attractions.map((attraction, idx) => (
            <div key={idx} className="bg-white dark:bg-slate-900 p-4 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-800 flex space-x-4 hover:border-brand-200 dark:hover:border-brand-800 transition-colors">
               {/* Use imagePrompt if available, falling back to name. Encoded by helper. */}
               <img src={getSmallImage(attraction.imagePrompt || attraction.name)} alt={attraction.name} className="w-20 h-20 rounded-xl object-cover flex-shrink-0 shadow-md" />
               <div>
                 <h4 className="font-bold text-slate-800 dark:text-slate-100 line-clamp-1">{attraction.name}</h4>
                 <p className="text-sm text-slate-500 dark:text-slate-400 mt-1 line-clamp-2 leading-relaxed">{attraction.benefit}</p>
               </div>
            </div>
          ))}
        </div>
      </div>

      {/* Map Context with Animated Markers */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-800 shadow-sm">
        {/* Visual Map Area */}
        <div className="relative h-48 bg-slate-200 dark:bg-slate-800 overflow-hidden group">
            {/* Background Map Image (Abstract) */}
            <img 
              src="https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=800" 
              alt="Map Background" 
              className="w-full h-full object-cover opacity-50 dark:opacity-30 group-hover:scale-105 transition-transform duration-1000 grayscale hover:grayscale-0"
            />
            
            {/* Animated Markers */}
            {/* Center Marker */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
               <div className="relative w-4 h-4">
                  <span className="absolute inline-flex h-full w-full rounded-full bg-brand-400 opacity-75 animate-ping"></span>
                  <span className="relative inline-flex rounded-full h-4 w-4 bg-brand-500 border-2 border-white dark:border-slate-900"></span>
               </div>
               <span className="mt-1 text-[10px] font-bold bg-white dark:bg-black/50 px-2 py-0.5 rounded-full shadow-sm backdrop-blur-md dark:text-white">City Center</span>
            </div>

            {/* Random Aesthetic Markers */}
            <div className="absolute top-1/4 left-1/4 flex flex-col items-center delay-75">
               <div className="relative w-3 h-3">
                  <span className="absolute inline-flex h-full w-full rounded-full bg-rose-400 opacity-75 animate-ping" style={{ animationDuration: '2s' }}></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-rose-500 border-2 border-white dark:border-slate-900"></span>
               </div>
            </div>

            <div className="absolute bottom-1/3 right-1/4 flex flex-col items-center delay-150">
               <div className="relative w-3 h-3">
                  <span className="absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75 animate-ping" style={{ animationDuration: '3s' }}></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-amber-500 border-2 border-white dark:border-slate-900"></span>
               </div>
            </div>
        </div>

        <div className="p-6">
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2 flex items-center">
            <MapIcon className="mr-2 text-brand-600 dark:text-brand-400" size={20} /> Lay of the Land
          </h3>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-sm">
            {guide.mapContext}
          </p>
        </div>
      </div>

      {/* Itinerary */}
      <div>
        <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-6 flex items-center">
          <Clock className="mr-2 text-brand-600 dark:text-brand-400" size={24} /> Perfect Day in {guide.city}
        </h3>
        <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-brand-200 before:via-brand-100 before:to-transparent dark:before:from-brand-900">
          {guide.itinerary.map((item, idx) => (
            <div key={idx} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
              
              {/* Timeline Dot */}
              <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 border-white dark:border-slate-950 bg-brand-500 text-white shadow-lg shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 absolute left-0 md:left-1/2 -translate-x-1/2 z-10">
                <span className="text-xs font-bold">{idx + 1}</span>
              </div>
              
              {/* Card */}
              <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 shadow-sm ml-auto md:ml-0 overflow-hidden hover:shadow-md transition-shadow">
                {/* Itinerary Image */}
                <div className="h-32 w-full overflow-hidden relative">
                  <img 
                    src={getItineraryImage(item.imagePrompt || item.activity)} 
                    alt={item.activity} 
                    className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-700"
                  />
                  <div className="absolute top-3 left-3 bg-black/50 backdrop-blur-md text-white text-xs font-bold px-3 py-1 rounded-full">
                    {item.time}
                  </div>
                </div>

                <div className="p-5">
                  <h4 className="font-bold text-lg text-slate-800 dark:text-slate-100 mb-2 leading-tight">{item.activity}</h4>
                  <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed mb-3">{item.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Local Tips Grid */}
      <div className="bg-slate-900 dark:bg-black/40 rounded-3xl p-8 text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 p-32 bg-brand-500/10 rounded-full blur-3xl -mr-16 -mt-16"></div>
        <div className="relative z-10">
          <h3 className="text-2xl font-bold mb-6 flex items-center">
            <Lightbulb className="mr-2 text-yellow-400" /> Travel Buddy Secrets
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div className="space-y-2">
              <h4 className="font-bold text-brand-300 flex items-center text-sm uppercase tracking-wide"><Utensils className="w-4 h-4 mr-2"/> Food & Drink</h4>
              <p className="text-sm text-slate-300 leading-relaxed">{guide.tips.food}</p>
            </div>
            <div className="space-y-2">
              <h4 className="font-bold text-brand-300 flex items-center text-sm uppercase tracking-wide"><ShieldCheck className="w-4 h-4 mr-2"/> Safety</h4>
              <p className="text-sm text-slate-300 leading-relaxed">{guide.tips.safety}</p>
            </div>
            <div className="space-y-2">
              <h4 className="font-bold text-brand-300 flex items-center text-sm uppercase tracking-wide"><Info className="w-4 h-4 mr-2"/> Culture</h4>
              <p className="text-sm text-slate-300 leading-relaxed">{guide.tips.culture}</p>
            </div>
            <div className="space-y-2">
              <h4 className="font-bold text-brand-300 flex items-center text-sm uppercase tracking-wide"><MapIcon className="w-4 h-4 mr-2"/> Pro Tip</h4>
              <p className="text-sm text-slate-300 leading-relaxed">{guide.tips.travel}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Share Modal */}
      {isShareModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
           <div className="bg-white dark:bg-slate-900 w-full max-w-sm rounded-3xl p-6 shadow-2xl relative animate-in zoom-in-95 duration-200">
              <button 
                onClick={() => setIsShareModalOpen(false)}
                className="absolute top-4 right-4 p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              >
                <X size={20} />
              </button>
              
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-6 text-center">Share Your Adventure</h3>
              
              <div className="grid grid-cols-2 gap-4">
                <button 
                  onClick={handleNativeShare}
                  className="flex flex-col items-center justify-center p-4 rounded-xl bg-slate-50 dark:bg-slate-800 hover:bg-brand-50 dark:hover:bg-brand-900/20 transition-colors group"
                >
                  <div className="p-3 bg-white dark:bg-slate-700 rounded-full shadow-sm mb-2 group-hover:scale-110 transition-transform">
                    <Share2 className="w-6 h-6 text-brand-600 dark:text-brand-400" />
                  </div>
                  <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">More Options</span>
                </button>
                
                <button 
                  onClick={handleWhatsAppShare}
                  className="flex flex-col items-center justify-center p-4 rounded-xl bg-slate-50 dark:bg-slate-800 hover:bg-green-50 dark:hover:bg-green-900/20 transition-colors group"
                >
                  <div className="p-3 bg-white dark:bg-slate-700 rounded-full shadow-sm mb-2 group-hover:scale-110 transition-transform">
                     <MessageCircle className="w-6 h-6 text-green-500" />
                  </div>
                  <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">WhatsApp</span>
                </button>

                <button 
                  onClick={handleTwitterShare}
                  className="flex flex-col items-center justify-center p-4 rounded-xl bg-slate-50 dark:bg-slate-800 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors group"
                >
                  <div className="p-3 bg-white dark:bg-slate-700 rounded-full shadow-sm mb-2 group-hover:scale-110 transition-transform">
                     <Twitter className="w-6 h-6 text-blue-400" />
                  </div>
                  <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">Twitter</span>
                </button>

                <button 
                  onClick={handleCopyLink}
                  className="flex flex-col items-center justify-center p-4 rounded-xl bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors group"
                >
                  <div className="p-3 bg-white dark:bg-slate-700 rounded-full shadow-sm mb-2 group-hover:scale-110 transition-transform">
                     <Link2 className="w-6 h-6 text-slate-500 dark:text-slate-400" />
                  </div>
                  <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">Copy Link</span>
                </button>
              </div>
           </div>
        </div>
      )}

      {/* Save Confirmation Modal */}
      {isSaveConfirmOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white dark:bg-slate-900 w-full max-w-sm rounded-3xl p-8 shadow-2xl animate-in zoom-in-95 duration-200 text-center">
            <div className="w-16 h-16 bg-brand-100 dark:bg-brand-900/30 rounded-full flex items-center justify-center mx-auto mb-6 text-brand-600 dark:text-brand-400">
               <AlertCircle size={32} />
            </div>
            <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Save this Trip?</h3>
            <p className="text-slate-500 dark:text-slate-400 mb-8">
              This will add {guide.city} to your saved adventures so you can access it offline later.
            </p>
            <div className="flex space-x-3">
              <Button variant="secondary" onClick={() => setIsSaveConfirmOpen(false)} className="flex-1">
                Cancel
              </Button>
              <Button variant="primary" onClick={handleConfirmSave} className="flex-1">
                Yes, Save It
              </Button>
            </div>
          </div>
        </div>
      )}

      <div className="h-8"></div>
    </div>
  );
};
